# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartext', '0002_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
