# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartext', '0003_auto_20170329_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
